import { getVisitedPositionCount, parseState } from './day06'

const testInput = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`

describe('getVisitedPositionCount', () => {
  it('works for test input', () => {
    expect(getVisitedPositionCount(parseState(testInput))).toBe(41)
  })
})
